### ISSUE TITLE
python找不到 文本输入框空间，出现超时

### ISSUE THREAD

**Issue by xiaolu-668** [cluic/wxauto#133]
大佬好：我在使用wxauto 进行微信信息自动化发送时，发现python无法找到文本框控件，日志如下谢谢：

C:\Users\Desktop\wxcc\venv\Scripts\python.exe C:\Users\33051\Desktop\wxcc\main.py 
2023-08-09 01:39:20.604 wxauto.py[56] SplitMessage -> Find Control Timeout(0s): {ControlType: ButtonControl}
2023-08-09 01:39:20.750 wxauto.py[56] SplitMessage -> Find Control Timeout(0s): {ControlType: ButtonControl}
2023-08-09 01:39:20.786 wxauto.py[56] SplitMessage -> Find Control Timeout(0s): {ControlType: ButtonControl}
2023-08-09 01:39:20.971 wxauto.py[56] SplitMessage -> Find Control Timeout(0s): {ControlType: ButtonControl}
2023-08-09 01:39:21.053 wxauto.py[56] SplitMessage -> Find Control Timeout(0s): {ControlType: ButtonControl}
2023-08-09 01:39:21.140 wxauto.py[56] SplitMessage -> Find Control Timeout(0s): {ControlType: ButtonControl}
2023-08-09 01:39:33.810 wxauto.py[218] SendMsg -> Find Control Timeout(10.0s): {Name: '输入', ControlType: EditControl}
Traceback (most recent call last):
  File "C:\UsersDesktop\wxcc\main.py", line 28, in <module>
    wx.SendMsg(msg)  # 向`文件传输助手`发送消息：你好~
  File "C:\Users\Desktop\wxcc\wxauto.py", line 218, in SendMsg
    self.EditMsg.SendKeys('{Ctrl}a', waitTime=0)
  File "C:\Users\Desktop\wxcc\venv\lib\site-packages\uiautomation\uiautomation.py", line 6743, in SendKeys
    self.SetFocus()
  File "C:\Users\Desktop\wxcc\venv\lib\site-packages\uiautomation\uiautomation.py", line 6213, in SetFocus
    return self.Element.SetFocus() == S_OK
  File "C:\Users\Desktop\wxcc\venv\lib\site-packages\uiautomation\uiautomation.py", line 6224, in Element
    self.Refind(maxSearchSeconds=TIME_OUT_SECOND, searchIntervalSeconds=self.searchInterval)
  File "C:\Users\Desktop\wxcc\venv\lib\site-packages\uiautomation\uiautomation.py", line 6475, in Refind
    raise LookupError('Find Control Timeout({}s): {}'.format(maxSearchSeconds, self.GetSearchPropertiesStr()))
LookupError: Find Control Timeout(10.0s): {Name: '输入', ControlType: EditControl}

Process finished with exit code 1

**Comment by gao0334** [comment]
您的来信已收到。gao

**Comment by xiaolu-668** [comment]
> 您的来信已收到。高

追加：这个wxauto 是使用pip安装的是不是包的问题

**Comment by wxfaith** [comment]
解决问题了吗？
