### ISSUE TITLE
这个能接收图片不

### ISSUE THREAD

**Issue by threescholars** [cluic/wxauto#147]
大佬，能研究下图片接收不

**Comment by cluic** [comment]
试下新版本，wx.GetAllMessage(savepic=True)可自动下载聊天图片

**Comment by TransparentsWorld** [comment]
> 试下新版本，wx.GetAllMessage(savepic=True)可自动下载聊天图片

试了，下载不了。

**Comment by TransparentsWorld** [comment]
> 试下新版本，wx.GetAllMessage(savepic=True)可自动下载聊天图片

大佬，试了下载不了图片。使用这个函数，会点击图片，然后再点击下载按钮，微信弹框之后，就没有下一步动作了。然后代码报错：
Traceback (most recent call last):
  File "D:\code\PycharmProjects\LazyCode\OfficeJob\src\test.py", line 7, in <module>
    wx.GetAllMessage(
  File "D:\application\python312\Lib\site-packages\wxauto\wxauto.py", line 503, in GetAllMessage
    msgs = self._getmsgs(MsgItems, savepic, savefile=savefile, savevoice=savevoice)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\application\python312\Lib\site-packages\wxauto\elements.py", line 84, in _getmsgs
    imgpath = self._download_pic(msg.control)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\application\python312\Lib\site-packages\wxauto\elements.py", line 103, in _download_pic
    savepath = imgobj.Save()
               ^^^^^^^^^^^^^
  File "D:\application\python312\Lib\site-packages\wxauto\elements.py", line 472, in Save
    raise TimeoutError('下载超时')
TimeoutError: 下载超时
