### ISSUE TITLE
3.9.8.15   几个问题代处理

### ISSUE THREAD

**Issue by bosunram** [cluic/wxauto#150]
Version: 3.9.8.15
Update: 2023-11-20

1、GetSessionList 时，如果用户当前有未读消息，读出的name  会变成【name+‘1条未读消息’】，用这个name 无法直接用作who去ChatWith

2、SendMsg(self, msg, who=None, clear=True)  方法中，who如果没有定义，会报错，如果定义了遇到【1】的问题会搜不到，而且每次都要搜索，太麻烦，最好可以跟老版本一样    省略默认为当前对话

Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\100.py", line 545, in <module>
    wx.SendMsg(x)
  File "C:\Python\Python37\lib\site-packages\wxauto\wxauto.py", line 166, in SendMsg
    editbox.SendKeys('{Ctrl}a', waitTime=0)
UnboundLocalError: local variable 'editbox' referenced before assignment

**Comment by cluic** [comment]
感谢反馈，我修复一下

**Comment by bosunram** [comment]
SendMsg   建议做成老版本那样省略默认为当前对话    刚试了一下    现在必须指定who  而且不是必须是好友才能搜到

**Comment by cluic** [comment]
已修复，并且增加自动获取新消息功能，有时间您测试一下看看

**Comment by bosunram** [comment]
修复的版本  运行报错
Traceback (most recent call last):
  File "C:\Users\Admin\Desktop\100.py", line 1, in <module>
    from wxauto import *
  File "C:\Python\Python37\lib\site-packages\wxauto\__init__.py", line 1, in <module>
    from .wxauto import WeChat
  File "C:\Python\Python37\lib\site-packages\wxauto\wxauto.py", line 7, in <module>
    from languages import *
ModuleNotFoundError: No module named 'languages'

**Comment by cluic** [comment]
不好意思，重新修复了

**Comment by bosunram** [comment]
你今天更新的2个版本我都测试过了   

1、GetSessionList  获取能够直接 wx.ChatWith( ) 的name，现在用的是字典，当然也能从字典的key 导出name来

2、现在的版本，用（1）取出的name  去 wx.ChatWith( )  会报错
Traceback (most recent call last):
  File "C:\Users\Bosunram\Desktop\100.py", line 14, in <module>
    wx.ChatWith(user)
  File "C:\Users\Bosunram\AppData\Local\Programs\Python\Python37\lib\site-packages\wxauto\wxauto.py", line 188, in ChatWith
    self.SessionBox.ListItemControl(Name=who1).Click(simulateMove=False)
UnboundLocalError: local variable 'who1' referenced before assignment

**Comment by cluic** [comment]
重新修改了

**Comment by bosunram** [comment]
line188    eles   ---》  else
