### ISSUE TITLE
请问程序在给几个人发送了信息后就报错了，该如何解决

### ISSUE THREAD

**Issue by clh1751764916** [cluic/wxauto#17]
尊敬的开发者，你好，我在用wxauto库来提醒他人进行疫情登记时，程序总是在发送前几个人的信息后就不再寻找聊天框了，接着就停止报错了，想请问一下如何解决这个问题。
代码：
from configparser import LegacyInterpolation
from wxauto import *
import time

wx = WeChat()
wx.GetSessionList()

leng=["张伟林","郑昊东","夏槟","郑剑锋","陈鹏理","范新森","罗鹏","邱斌","黄孝鹏","洪宇","吴昊彬",]

for i in leng:
  msg = '1'
  who = i

  wx.ChatWith(who)  
  wx.SendMsg(msg)  
报错：
Traceback (most recent call last):
  File "d:/爬虫框架/120.py", line 20, in <module>
    wx.ChatWith(who)  # 打开`文件传输助手`聊天窗口
  File "D:\anaconda3\lib\site-packages\wxauto\wxauto.py", line 196, in ChatWith
    rollresult = roll_to()
  File "D:\anaconda3\lib\site-packages\wxauto\wxauto.py", line 193, in roll_to
    self.SessionList.ListItemControl(Name=who).Click(simulateMove=False)
  File "D:\anaconda3\lib\site-packages\uiautomation\uiautomation.py", line 6542, in Click
    point = self.MoveCursorToInnerPos(x, y, ratioX, ratioY, simulateMove)
  File "D:\anaconda3\lib\site-packages\uiautomation\uiautomation.py", line 6503, in MoveCursorToInnerPos
    rect = self.BoundingRectangle
  File "D:\anaconda3\lib\site-packages\uiautomation\uiautomation.py", line 5906, in BoundingRectangle
    rect = self.Element.CurrentBoundingRectangle
  File "D:\anaconda3\lib\site-packages\uiautomation\uiautomation.py", line 6220, in Element
    self.Refind(maxSearchSeconds=TIME_OUT_SECOND, searchIntervalSeconds=self.searchInterval)
  File "D:\anaconda3\lib\site-packages\uiautomation\uiautomation.py", line 6471, in Refind
    raise LookupError('Find Control Timeout({}s): {}'.format(maxSearchSeconds, self.GetSearchPropertiesStr()))
LookupError: Find Control Timeout(10s): {Name: '陈鹏理', ControlType: ListItemControl}

**Comment by clh1751764916** [comment]
用wx.Search()方法可以直接查找，不会进行滚动聊天栏查找，就不会报错了
