### ISSUE TITLE
每天定时发送信息时发现超时问题

### ISSUE THREAD

**Issue by CIDE-0409** [cluic/wxauto#186]
作者你好，我现在写了一个脚本，是定时每天9点发送一段文字给微信，然后发现报这个错误
Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\github-cve-monitor-master\github_cve_monitor.py", line 452, in wechat
    wechatbot.SendMsg("".join(result), who)
  File "C:\Users\Administrator\Desktop\github-cve-monitor-master\wxauto\wxauto\wxauto.py", line 244, in SendMsg
    raise TimeoutError(f'发送消息超时 --> {editbox.Name} - {msg}')
 
 然后我发现在手动运行发送信息的代码时，是能正常发送的，这是什么问题呢。

**Comment by CIDE-0409** [comment]
是有可能发送的字符太长导致的吗？可是我直接运行脚本后，发现是能正常发送的。

**Comment by zhuwuhong** [comment]
可以把你代码发出来看看吗
