### ISSUE TITLE
demo.py报错

### ISSUE THREAD

**Issue by flyphoenix456** [cluic/wxauto#233]
微信3.9.8.15
Traceback (most recent call last):
  File "D:\Desktop\wxauto\demo.py", line 8, in <module>
    wx.SendMsg(f'wxauto测试{i+1}', who)
  File "D:\Desktop\wxauto\wxauto\wxauto.py", line 312, in SendMsg
    raise TimeoutError(f'发送消息超时 --> {editbox.Name} - {msg}')
TimeoutError: 发送消息超时 --> 文件传输助手 - wxauto测试1

**Comment by Squirrel963** [comment]
wx.SendMsg（f'wxauto测试{i+1}'， who=_"somebody"_）
在第2个参数后面加一个赋值试试
