### ISSUE TITLE
粘贴和发送失败，会卡着，最后timeout ，wechat version 3.9.0.28,这个要怎么改，有遇到过？

### ISSUE THREAD

**Issue by yjiangithub** [cluic/wxauto#94]
wxauto.py[209] SendMsg -> Find Control Timeout(10s): {Name: '输入', ControlType: EditControl}
Traceback (most recent call last):
  File "C:\Users\Administrator\.spyder-py3\getMessage2.py", line 41, in <module>
    wx.SendClipboard()   # 发送剪贴板的内容，类似于Ctrl + V
  File "C:\Users\Administrator\.spyder-py3\wxauto.py", line 249, in SendClipboard
    self.SendMsg('{Ctrl}v')
  File "C:\Users\Administrator\.spyder-py3\wxauto.py", line 209, in SendMsg
    self.EditMsg.SendKeys('{Ctrl}a', waitTime=0)
  File "C:\Program Files (x86)-george\Python392\lib\site-packages\uiautomation\uiautomation.py", line 6742, in SendKeys
    self.SetFocus()
  File "C:\Program Files (x86)-george\Python392\lib\site-packages\uiautomation\uiautomation.py", line 6212, in SetFocus
    return self.Element.SetFocus() == S_OK
  File "C:\Program Files (x86)-george\Python392\lib\site-packages\uiautomation\uiautomation.py", line 6223, in Element
    self.Refind(maxSearchSeconds=TIME_OUT_SECOND, searchIntervalSeconds=self.searchInterval)
  File "C:\Program Files (x86)-george\Python392\lib\site-packages\uiautomation\uiautomation.py", line 6474, in Refind
    raise LookupError('Find Control Timeout({}s): {}'.format(maxSearchSeconds, self.GetSearchPropertiesStr()))
LookupError: Find Control Timeout(10s): {Name: '输入', ControlType: EditControl}

**Comment by maodouxj** [comment]
我也遇到一样的问题，没找到解决方案，请教群里的大神，如何解决，谢谢！

**Comment by gao0334** [comment]
你好，这个不是我的问题。应该是其他人的。


我的问题是：WXAUTO能实现自动读取微信新消息的功能吗？


比如别人给我微信发了消息，到时程序能识别出新消息，把发送人的ID或者用户名，还有所发内容都读出来。


等于要达到微信自动应答功能，或者自动回复机器人那样。


谢谢！






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "cluic/wxauto"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月22日(星期一) 下午3:04
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [cluic/wxauto] 粘贴和发送失败，会卡着，最后timeout ，wechat version 3.9.0.28,这个要怎么改，有遇到过？ (Issue #94)





 
要不换个低版本的微信试试？
